/*
Digiseg API

### Digiseg API documentation  # Introduction  This API let you harness the power of Digisegs powerful and tracking-free segmentation engine.  Audiences by Digiseg are available in 50+ countries, probablistically mapping neighborhood characteristics to the IP addresses observed on the internet - Household targeting & measurement for the post-cookie world.  ## Developer SDKs  In addition to using these APIs directly through any HTTP client, we provide a set of API client SDKs for popular programming languages:  <div class=\"api-clients\">   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-python\">     <i class=\"api-client-sdk-logo devicon-python-plain\"></i>     <p>API client for<br/>Python</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-ts\">     <i class=\"api-client-sdk-logo devicon-typescript-plain\"></i>     <p>API client for<br/>TypeScript</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-go\">     <i class=\"api-client-sdk-logo devicon-go-original-wordmark\"></i>     <p>API client for<br/>Go</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-dotnet\">     <i class=\"api-client-sdk-logo devicon-dot-net-plain\"></i>     <p>API client for<br/>.NET</p>   </a> </div> <div class=\"api-clients-breaker\" /> 

API version: 1.0.0
Contact: support@digiseg.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListDataMonthlyUsage200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDataMonthlyUsage200Response{}

// ListDataMonthlyUsage200Response struct for ListDataMonthlyUsage200Response
type ListDataMonthlyUsage200Response struct {
	Data []DataMonthlyUsage `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListDataMonthlyUsage200Response ListDataMonthlyUsage200Response

// NewListDataMonthlyUsage200Response instantiates a new ListDataMonthlyUsage200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDataMonthlyUsage200Response() *ListDataMonthlyUsage200Response {
	this := ListDataMonthlyUsage200Response{}
	return &this
}

// NewListDataMonthlyUsage200ResponseWithDefaults instantiates a new ListDataMonthlyUsage200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDataMonthlyUsage200ResponseWithDefaults() *ListDataMonthlyUsage200Response {
	this := ListDataMonthlyUsage200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListDataMonthlyUsage200Response) GetData() []DataMonthlyUsage {
	if o == nil || IsNil(o.Data) {
		var ret []DataMonthlyUsage
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDataMonthlyUsage200Response) GetDataOk() ([]DataMonthlyUsage, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListDataMonthlyUsage200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []DataMonthlyUsage and assigns it to the Data field.
func (o *ListDataMonthlyUsage200Response) SetData(v []DataMonthlyUsage) {
	o.Data = v
}

func (o ListDataMonthlyUsage200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDataMonthlyUsage200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListDataMonthlyUsage200Response) UnmarshalJSON(data []byte) (err error) {
	varListDataMonthlyUsage200Response := _ListDataMonthlyUsage200Response{}

	err = json.Unmarshal(data, &varListDataMonthlyUsage200Response)

	if err != nil {
		return err
	}

	*o = ListDataMonthlyUsage200Response(varListDataMonthlyUsage200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListDataMonthlyUsage200Response struct {
	value *ListDataMonthlyUsage200Response
	isSet bool
}

func (v NullableListDataMonthlyUsage200Response) Get() *ListDataMonthlyUsage200Response {
	return v.value
}

func (v *NullableListDataMonthlyUsage200Response) Set(val *ListDataMonthlyUsage200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListDataMonthlyUsage200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListDataMonthlyUsage200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDataMonthlyUsage200Response(val *ListDataMonthlyUsage200Response) *NullableListDataMonthlyUsage200Response {
	return &NullableListDataMonthlyUsage200Response{value: val, isSet: true}
}

func (v NullableListDataMonthlyUsage200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDataMonthlyUsage200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


