/*
Digiseg API

### Digiseg API documentation  # Introduction  This API let you harness the power of Digisegs powerful and tracking-free segmentation engine.  Audiences by Digiseg are available in 50+ countries, probablistically mapping neighborhood characteristics to the IP addresses observed on the internet - Household targeting & measurement for the post-cookie world.  For a catalog of Digisegs audiences, refer to the [Audience list](https://digiseg.io/audiences-list).  There is also an interactive [Audience builder](https://digiseg.io/cookieless-audience-builder/) which lets you discover the targeting reach and power of combining various household characteristics into composite audiences. 

API version: 1.0.0
Contact: support@digiseg.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ResolveAudiencesOfMultipleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResolveAudiencesOfMultipleRequest{}

// ResolveAudiencesOfMultipleRequest struct for ResolveAudiencesOfMultipleRequest
type ResolveAudiencesOfMultipleRequest struct {
	Queries []ResolveAudiencesOfMultipleRequestItem `json:"queries"`
}

type _ResolveAudiencesOfMultipleRequest ResolveAudiencesOfMultipleRequest

// NewResolveAudiencesOfMultipleRequest instantiates a new ResolveAudiencesOfMultipleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResolveAudiencesOfMultipleRequest(queries []ResolveAudiencesOfMultipleRequestItem) *ResolveAudiencesOfMultipleRequest {
	this := ResolveAudiencesOfMultipleRequest{}
	this.Queries = queries
	return &this
}

// NewResolveAudiencesOfMultipleRequestWithDefaults instantiates a new ResolveAudiencesOfMultipleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResolveAudiencesOfMultipleRequestWithDefaults() *ResolveAudiencesOfMultipleRequest {
	this := ResolveAudiencesOfMultipleRequest{}
	return &this
}

// GetQueries returns the Queries field value
func (o *ResolveAudiencesOfMultipleRequest) GetQueries() []ResolveAudiencesOfMultipleRequestItem {
	if o == nil {
		var ret []ResolveAudiencesOfMultipleRequestItem
		return ret
	}

	return o.Queries
}

// GetQueriesOk returns a tuple with the Queries field value
// and a boolean to check if the value has been set.
func (o *ResolveAudiencesOfMultipleRequest) GetQueriesOk() ([]ResolveAudiencesOfMultipleRequestItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Queries, true
}

// SetQueries sets field value
func (o *ResolveAudiencesOfMultipleRequest) SetQueries(v []ResolveAudiencesOfMultipleRequestItem) {
	o.Queries = v
}

func (o ResolveAudiencesOfMultipleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResolveAudiencesOfMultipleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["queries"] = o.Queries
	return toSerialize, nil
}

func (o *ResolveAudiencesOfMultipleRequest) UnmarshalJSON(bytes []byte) (err error) {
    // This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"queries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResolveAudiencesOfMultipleRequest := _ResolveAudiencesOfMultipleRequest{}

	err = json.Unmarshal(bytes, &varResolveAudiencesOfMultipleRequest)

	if err != nil {
		return err
	}

	*o = ResolveAudiencesOfMultipleRequest(varResolveAudiencesOfMultipleRequest)

	return err
}

type NullableResolveAudiencesOfMultipleRequest struct {
	value *ResolveAudiencesOfMultipleRequest
	isSet bool
}

func (v NullableResolveAudiencesOfMultipleRequest) Get() *ResolveAudiencesOfMultipleRequest {
	return v.value
}

func (v *NullableResolveAudiencesOfMultipleRequest) Set(val *ResolveAudiencesOfMultipleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableResolveAudiencesOfMultipleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableResolveAudiencesOfMultipleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResolveAudiencesOfMultipleRequest(val *ResolveAudiencesOfMultipleRequest) *NullableResolveAudiencesOfMultipleRequest {
	return &NullableResolveAudiencesOfMultipleRequest{value: val, isSet: true}
}

func (v NullableResolveAudiencesOfMultipleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResolveAudiencesOfMultipleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


