/*
Digiseg API

### Digiseg API documentation  # Introduction  This API let you harness the power of Digisegs powerful and tracking-free segmentation engine.  Audiences by Digiseg are available in 50+ countries, probablistically mapping neighborhood characteristics to the IP addresses observed on the internet - Household targeting & measurement for the post-cookie world.  ## Developer SDKs  In addition to using these APIs directly through any HTTP client, we provide a set of API client SDKs for popular programming languages:  <div class=\"api-clients\">   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-python\">     <i class=\"api-client-sdk-logo devicon-python-plain\"></i>     <p>API client for Python</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-ts\">     <i class=\"api-client-sdk-logo devicon-typescript-plain\"></i>     <p>API client for TypeScript</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-go\">     <i class=\"api-client-sdk-logo devicon-go-original-wordmark\"></i>     <p>API client for Go</p>   </a> </div> <div class=\"api-clients-breaker\" /> 

API version: 1.0.0
Contact: support@digiseg.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// UserIncludeParam the model 'UserIncludeParam'
type UserIncludeParam string

// List of UserIncludeParam
const (
	USERINCLUDEPARAM_NONE UserIncludeParam = "none"
	USERINCLUDEPARAM_SUBSCRIPTIONS UserIncludeParam = "subscriptions"
	USERINCLUDEPARAM_ACCOUNT UserIncludeParam = "account"
)

// All allowed values of UserIncludeParam enum
var AllowedUserIncludeParamEnumValues = []UserIncludeParam{
	"none",
	"subscriptions",
	"account",
}

func (v *UserIncludeParam) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := UserIncludeParam(value)
	for _, existing := range AllowedUserIncludeParamEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid UserIncludeParam", value)
}

// NewUserIncludeParamFromValue returns a pointer to a valid UserIncludeParam
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewUserIncludeParamFromValue(v string) (*UserIncludeParam, error) {
	ev := UserIncludeParam(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for UserIncludeParam: valid values are %v", v, AllowedUserIncludeParamEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v UserIncludeParam) IsValid() bool {
	for _, existing := range AllowedUserIncludeParamEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to UserIncludeParam value
func (v UserIncludeParam) Ptr() *UserIncludeParam {
	return &v
}

type NullableUserIncludeParam struct {
	value *UserIncludeParam
	isSet bool
}

func (v NullableUserIncludeParam) Get() *UserIncludeParam {
	return v.value
}

func (v *NullableUserIncludeParam) Set(val *UserIncludeParam) {
	v.value = val
	v.isSet = true
}

func (v NullableUserIncludeParam) IsSet() bool {
	return v.isSet
}

func (v *NullableUserIncludeParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserIncludeParam(val *UserIncludeParam) *NullableUserIncludeParam {
	return &NullableUserIncludeParam{value: val, isSet: true}
}

func (v NullableUserIncludeParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserIncludeParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

