/*
Digiseg API

### Digiseg API documentation  # Introduction  This API let you harness the power of Digisegs powerful and tracking-free segmentation engine.  Audiences by Digiseg are available in 50+ countries, probablistically mapping neighborhood characteristics to the IP addresses observed on the internet - Household targeting & measurement for the post-cookie world.  ## Developer SDKs  In addition to using these APIs directly through any HTTP client, we provide a set of API client SDKs for popular programming languages:  <div class=\"api-clients\">   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-python\">     <i class=\"api-client-sdk-logo devicon-python-plain\"></i>     <p>API client for Python</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-ts\">     <i class=\"api-client-sdk-logo devicon-typescript-plain\"></i>     <p>API client for TypeScript</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-go\">     <i class=\"api-client-sdk-logo devicon-go-original-wordmark\"></i>     <p>API client for Go</p>   </a> </div> <div class=\"api-clients-breaker\" /> 

API version: 1.0.0
Contact: support@digiseg.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AccountCreationAux type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountCreationAux{}

// AccountCreationAux struct for AccountCreationAux
type AccountCreationAux struct {
	Owner *AccountOwnerCreation `json:"owner,omitempty"`
	// ID of the user who is the ultimate owner of the account. Deprecated in favor of the `owner` role of the user's account membership.
	// Deprecated
	OwnerId *string `json:"owner_id,omitempty"`
	// The email address to send billing information to. Requires `owner` role to change.
	BillingEmail *string `json:"billing_email,omitempty"`
	BillingAddress *PostalAddress `json:"billing_address,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AccountCreationAux AccountCreationAux

// NewAccountCreationAux instantiates a new AccountCreationAux object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountCreationAux() *AccountCreationAux {
	this := AccountCreationAux{}
	return &this
}

// NewAccountCreationAuxWithDefaults instantiates a new AccountCreationAux object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountCreationAuxWithDefaults() *AccountCreationAux {
	this := AccountCreationAux{}
	return &this
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *AccountCreationAux) GetOwner() AccountOwnerCreation {
	if o == nil || IsNil(o.Owner) {
		var ret AccountOwnerCreation
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountCreationAux) GetOwnerOk() (*AccountOwnerCreation, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *AccountCreationAux) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given AccountOwnerCreation and assigns it to the Owner field.
func (o *AccountCreationAux) SetOwner(v AccountOwnerCreation) {
	o.Owner = &v
}

// GetOwnerId returns the OwnerId field value if set, zero value otherwise.
// Deprecated
func (o *AccountCreationAux) GetOwnerId() string {
	if o == nil || IsNil(o.OwnerId) {
		var ret string
		return ret
	}
	return *o.OwnerId
}

// GetOwnerIdOk returns a tuple with the OwnerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *AccountCreationAux) GetOwnerIdOk() (*string, bool) {
	if o == nil || IsNil(o.OwnerId) {
		return nil, false
	}
	return o.OwnerId, true
}

// HasOwnerId returns a boolean if a field has been set.
func (o *AccountCreationAux) HasOwnerId() bool {
	if o != nil && !IsNil(o.OwnerId) {
		return true
	}

	return false
}

// SetOwnerId gets a reference to the given string and assigns it to the OwnerId field.
// Deprecated
func (o *AccountCreationAux) SetOwnerId(v string) {
	o.OwnerId = &v
}

// GetBillingEmail returns the BillingEmail field value if set, zero value otherwise.
func (o *AccountCreationAux) GetBillingEmail() string {
	if o == nil || IsNil(o.BillingEmail) {
		var ret string
		return ret
	}
	return *o.BillingEmail
}

// GetBillingEmailOk returns a tuple with the BillingEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountCreationAux) GetBillingEmailOk() (*string, bool) {
	if o == nil || IsNil(o.BillingEmail) {
		return nil, false
	}
	return o.BillingEmail, true
}

// HasBillingEmail returns a boolean if a field has been set.
func (o *AccountCreationAux) HasBillingEmail() bool {
	if o != nil && !IsNil(o.BillingEmail) {
		return true
	}

	return false
}

// SetBillingEmail gets a reference to the given string and assigns it to the BillingEmail field.
func (o *AccountCreationAux) SetBillingEmail(v string) {
	o.BillingEmail = &v
}

// GetBillingAddress returns the BillingAddress field value if set, zero value otherwise.
func (o *AccountCreationAux) GetBillingAddress() PostalAddress {
	if o == nil || IsNil(o.BillingAddress) {
		var ret PostalAddress
		return ret
	}
	return *o.BillingAddress
}

// GetBillingAddressOk returns a tuple with the BillingAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountCreationAux) GetBillingAddressOk() (*PostalAddress, bool) {
	if o == nil || IsNil(o.BillingAddress) {
		return nil, false
	}
	return o.BillingAddress, true
}

// HasBillingAddress returns a boolean if a field has been set.
func (o *AccountCreationAux) HasBillingAddress() bool {
	if o != nil && !IsNil(o.BillingAddress) {
		return true
	}

	return false
}

// SetBillingAddress gets a reference to the given PostalAddress and assigns it to the BillingAddress field.
func (o *AccountCreationAux) SetBillingAddress(v PostalAddress) {
	o.BillingAddress = &v
}

func (o AccountCreationAux) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountCreationAux) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	if !IsNil(o.OwnerId) {
		toSerialize["owner_id"] = o.OwnerId
	}
	if !IsNil(o.BillingEmail) {
		toSerialize["billing_email"] = o.BillingEmail
	}
	if !IsNil(o.BillingAddress) {
		toSerialize["billing_address"] = o.BillingAddress
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AccountCreationAux) UnmarshalJSON(data []byte) (err error) {
	varAccountCreationAux := _AccountCreationAux{}

	err = json.Unmarshal(data, &varAccountCreationAux)

	if err != nil {
		return err
	}

	*o = AccountCreationAux(varAccountCreationAux)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "owner")
		delete(additionalProperties, "owner_id")
		delete(additionalProperties, "billing_email")
		delete(additionalProperties, "billing_address")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAccountCreationAux struct {
	value *AccountCreationAux
	isSet bool
}

func (v NullableAccountCreationAux) Get() *AccountCreationAux {
	return v.value
}

func (v *NullableAccountCreationAux) Set(val *AccountCreationAux) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountCreationAux) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountCreationAux) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountCreationAux(val *AccountCreationAux) *NullableAccountCreationAux {
	return &NullableAccountCreationAux{value: val, isSet: true}
}

func (v NullableAccountCreationAux) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountCreationAux) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


