/*
Digiseg API

### Digiseg API documentation  # Introduction  This API let you harness the power of Digisegs powerful and tracking-free segmentation engine.  Audiences by Digiseg are available in 50+ countries, probablistically mapping neighborhood characteristics to the IP addresses observed on the internet - Household targeting & measurement for the post-cookie world.  ## Developer SDKs  In addition to using these APIs directly through any HTTP client, we provide a set of API client SDKs for popular programming languages:  <div class=\"api-clients\">   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-python\">     <i class=\"api-client-sdk-logo devicon-python-plain\"></i>     <p>API client for Python</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-ts\">     <i class=\"api-client-sdk-logo devicon-typescript-plain\"></i>     <p>API client for TypeScript</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-go\">     <i class=\"api-client-sdk-logo devicon-go-original-wordmark\"></i>     <p>API client for Go</p>   </a> </div> <div class=\"api-clients-breaker\" /> 

API version: 1.0.0
Contact: support@digiseg.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the StudyPermissions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StudyPermissions{}

// StudyPermissions Provides information about the current user's permissions of a study
type StudyPermissions struct {
	// Can the current user GET (read) study information?
	Get bool `json:"get"`
	// Can the current user PUT (update) study information?
	Put bool `json:"put"`
	// Can the current user DELETE the study?
	Delete bool `json:"delete"`
	AdditionalProperties map[string]interface{}
}

type _StudyPermissions StudyPermissions

// NewStudyPermissions instantiates a new StudyPermissions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStudyPermissions(get bool, put bool, delete bool) *StudyPermissions {
	this := StudyPermissions{}
	this.Get = get
	this.Put = put
	this.Delete = delete
	return &this
}

// NewStudyPermissionsWithDefaults instantiates a new StudyPermissions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStudyPermissionsWithDefaults() *StudyPermissions {
	this := StudyPermissions{}
	return &this
}

// GetGet returns the Get field value
func (o *StudyPermissions) GetGet() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Get
}

// GetGetOk returns a tuple with the Get field value
// and a boolean to check if the value has been set.
func (o *StudyPermissions) GetGetOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Get, true
}

// SetGet sets field value
func (o *StudyPermissions) SetGet(v bool) {
	o.Get = v
}

// GetPut returns the Put field value
func (o *StudyPermissions) GetPut() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Put
}

// GetPutOk returns a tuple with the Put field value
// and a boolean to check if the value has been set.
func (o *StudyPermissions) GetPutOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Put, true
}

// SetPut sets field value
func (o *StudyPermissions) SetPut(v bool) {
	o.Put = v
}

// GetDelete returns the Delete field value
func (o *StudyPermissions) GetDelete() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Delete
}

// GetDeleteOk returns a tuple with the Delete field value
// and a boolean to check if the value has been set.
func (o *StudyPermissions) GetDeleteOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Delete, true
}

// SetDelete sets field value
func (o *StudyPermissions) SetDelete(v bool) {
	o.Delete = v
}

func (o StudyPermissions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StudyPermissions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["get"] = o.Get
	toSerialize["put"] = o.Put
	toSerialize["delete"] = o.Delete

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StudyPermissions) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"get",
		"put",
		"delete",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStudyPermissions := _StudyPermissions{}

	err = json.Unmarshal(data, &varStudyPermissions)

	if err != nil {
		return err
	}

	*o = StudyPermissions(varStudyPermissions)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "get")
		delete(additionalProperties, "put")
		delete(additionalProperties, "delete")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStudyPermissions struct {
	value *StudyPermissions
	isSet bool
}

func (v NullableStudyPermissions) Get() *StudyPermissions {
	return v.value
}

func (v *NullableStudyPermissions) Set(val *StudyPermissions) {
	v.value = val
	v.isSet = true
}

func (v NullableStudyPermissions) IsSet() bool {
	return v.isSet
}

func (v *NullableStudyPermissions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStudyPermissions(val *StudyPermissions) *NullableStudyPermissions {
	return &NullableStudyPermissions{value: val, isSet: true}
}

func (v NullableStudyPermissions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStudyPermissions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


