/*
Digiseg API

### Digiseg API documentation  # Introduction  This API let you harness the power of Digisegs powerful and tracking-free segmentation engine.  Audiences by Digiseg are available in 50+ countries, probablistically mapping neighborhood characteristics to the IP addresses observed on the internet - Household targeting & measurement for the post-cookie world.  ## Developer SDKs  In addition to using these APIs directly through any HTTP client, we provide a set of API client SDKs for popular programming languages:  <div class=\"api-clients\">   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-python\">     <i class=\"api-client-sdk-logo devicon-python-plain\"></i>     <p>API client for Python</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-go\">     <i class=\"api-client-sdk-logo devicon-go-original-wordmark\"></i>     <p>API client for Go</p>   </a> </div> <div class=\"api-clients-breaker\" />  ## Audience taxonomy  For a catalog of Digisegs audiences, refer to the [Audience list](https://digiseg.io/audiences-list).  There is also an interactive [Audience builder](https://digiseg.io/cookieless-audience-builder/) which lets you discover the targeting reach and power of combining various household characteristics into composite audiences. 

API version: 1.0.0
Contact: support@digiseg.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AccountCreationAux type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountCreationAux{}

// AccountCreationAux struct for AccountCreationAux
type AccountCreationAux struct {
	Owner *AccountOwnerCreation `json:"owner,omitempty"`
}

// NewAccountCreationAux instantiates a new AccountCreationAux object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountCreationAux() *AccountCreationAux {
	this := AccountCreationAux{}
	return &this
}

// NewAccountCreationAuxWithDefaults instantiates a new AccountCreationAux object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountCreationAuxWithDefaults() *AccountCreationAux {
	this := AccountCreationAux{}
	return &this
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *AccountCreationAux) GetOwner() AccountOwnerCreation {
	if o == nil || IsNil(o.Owner) {
		var ret AccountOwnerCreation
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountCreationAux) GetOwnerOk() (*AccountOwnerCreation, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *AccountCreationAux) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given AccountOwnerCreation and assigns it to the Owner field.
func (o *AccountCreationAux) SetOwner(v AccountOwnerCreation) {
	o.Owner = &v
}

func (o AccountCreationAux) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountCreationAux) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	return toSerialize, nil
}

type NullableAccountCreationAux struct {
	value *AccountCreationAux
	isSet bool
}

func (v NullableAccountCreationAux) Get() *AccountCreationAux {
	return v.value
}

func (v *NullableAccountCreationAux) Set(val *AccountCreationAux) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountCreationAux) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountCreationAux) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountCreationAux(val *AccountCreationAux) *NullableAccountCreationAux {
	return &NullableAccountCreationAux{value: val, isSet: true}
}

func (v NullableAccountCreationAux) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountCreationAux) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


