/*
Digiseg API

### Digiseg API documentation  # Introduction  This API let you harness the power of Digisegs powerful and tracking-free segmentation engine.  Audiences by Digiseg are available in 50+ countries, probablistically mapping neighborhood characteristics to the IP addresses observed on the internet - Household targeting & measurement for the post-cookie world.  ## Developer SDKs  In addition to using these APIs directly through any HTTP client, we provide a set of API client SDKs for popular programming languages:  <div class=\"api-clients\">   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-python\">     <i class=\"api-client-sdk-logo devicon-python-plain\"></i>     <p>API client for<br/>Python</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-ts\">     <i class=\"api-client-sdk-logo devicon-typescript-plain\"></i>     <p>API client for<br/>TypeScript</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-go\">     <i class=\"api-client-sdk-logo devicon-go-original-wordmark\"></i>     <p>API client for<br/>Go</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-dotnet\">     <i class=\"api-client-sdk-logo devicon-dot-net-plain\"></i>     <p>API client for<br/>.NET</p>   </a> </div> <div class=\"api-clients-breaker\" /> 

API version: 1.0.0
Contact: support@digiseg.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AudienceResponse1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AudienceResponse1{}

// AudienceResponse1 struct for AudienceResponse1
type AudienceResponse1 struct {
	Data *AudienceItem `json:"data,omitempty"`
	Meta *AudienceResponseMeta `json:"meta,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AudienceResponse1 AudienceResponse1

// NewAudienceResponse1 instantiates a new AudienceResponse1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAudienceResponse1() *AudienceResponse1 {
	this := AudienceResponse1{}
	return &this
}

// NewAudienceResponse1WithDefaults instantiates a new AudienceResponse1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAudienceResponse1WithDefaults() *AudienceResponse1 {
	this := AudienceResponse1{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AudienceResponse1) GetData() AudienceItem {
	if o == nil || IsNil(o.Data) {
		var ret AudienceItem
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AudienceResponse1) GetDataOk() (*AudienceItem, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AudienceResponse1) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given AudienceItem and assigns it to the Data field.
func (o *AudienceResponse1) SetData(v AudienceItem) {
	o.Data = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *AudienceResponse1) GetMeta() AudienceResponseMeta {
	if o == nil || IsNil(o.Meta) {
		var ret AudienceResponseMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AudienceResponse1) GetMetaOk() (*AudienceResponseMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *AudienceResponse1) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given AudienceResponseMeta and assigns it to the Meta field.
func (o *AudienceResponse1) SetMeta(v AudienceResponseMeta) {
	o.Meta = &v
}

func (o AudienceResponse1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AudienceResponse1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AudienceResponse1) UnmarshalJSON(data []byte) (err error) {
	varAudienceResponse1 := _AudienceResponse1{}

	err = json.Unmarshal(data, &varAudienceResponse1)

	if err != nil {
		return err
	}

	*o = AudienceResponse1(varAudienceResponse1)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "meta")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAudienceResponse1 struct {
	value *AudienceResponse1
	isSet bool
}

func (v NullableAudienceResponse1) Get() *AudienceResponse1 {
	return v.value
}

func (v *NullableAudienceResponse1) Set(val *AudienceResponse1) {
	v.value = val
	v.isSet = true
}

func (v NullableAudienceResponse1) IsSet() bool {
	return v.isSet
}

func (v *NullableAudienceResponse1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAudienceResponse1(val *AudienceResponse1) *NullableAudienceResponse1 {
	return &NullableAudienceResponse1{value: val, isSet: true}
}

func (v NullableAudienceResponse1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAudienceResponse1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


