/*
Digiseg API

### Digiseg API documentation  # Introduction  This API let you harness the power of Digisegs powerful and tracking-free segmentation engine.  Audiences by Digiseg are available in 50+ countries, probablistically mapping neighborhood characteristics to the IP addresses observed on the internet - Household targeting & measurement for the post-cookie world.  ## Developer SDKs  In addition to using these APIs directly through any HTTP client, we provide a set of API client SDKs for popular programming languages:  <div class=\"api-clients\">   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-python\">     <i class=\"api-client-sdk-logo devicon-python-plain\"></i>     <p>API client for Python</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-ts\">     <i class=\"api-client-sdk-logo devicon-typescript-plain\"></i>     <p>API client for TypeScript</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-go\">     <i class=\"api-client-sdk-logo devicon-go-original-wordmark\"></i>     <p>API client for Go</p>   </a> </div> <div class=\"api-clients-breaker\" /> 

API version: 1.0.0
Contact: support@digiseg.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// UserSortOption the model 'UserSortOption'
type UserSortOption string

// List of UserSortOption
const (
	USERSORTOPTION_CREATED_AT UserSortOption = "created_at"
	USERSORTOPTION_CREATED_AT2 UserSortOption = "-created_at"
	USERSORTOPTION_NAME UserSortOption = "name"
	USERSORTOPTION_NAME2 UserSortOption = "-name"
	USERSORTOPTION_LOGGED_IN_AT UserSortOption = "logged_in_at"
	USERSORTOPTION_LOGGED_IN_AT2 UserSortOption = "-logged_in_at"
)

// All allowed values of UserSortOption enum
var AllowedUserSortOptionEnumValues = []UserSortOption{
	"created_at",
	"-created_at",
	"name",
	"-name",
	"logged_in_at",
	"-logged_in_at",
}

func (v *UserSortOption) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := UserSortOption(value)
	for _, existing := range AllowedUserSortOptionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid UserSortOption", value)
}

// NewUserSortOptionFromValue returns a pointer to a valid UserSortOption
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewUserSortOptionFromValue(v string) (*UserSortOption, error) {
	ev := UserSortOption(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for UserSortOption: valid values are %v", v, AllowedUserSortOptionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v UserSortOption) IsValid() bool {
	for _, existing := range AllowedUserSortOptionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to UserSortOption value
func (v UserSortOption) Ptr() *UserSortOption {
	return &v
}

type NullableUserSortOption struct {
	value *UserSortOption
	isSet bool
}

func (v NullableUserSortOption) Get() *UserSortOption {
	return v.value
}

func (v *NullableUserSortOption) Set(val *UserSortOption) {
	v.value = val
	v.isSet = true
}

func (v NullableUserSortOption) IsSet() bool {
	return v.isSet
}

func (v *NullableUserSortOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserSortOption(val *UserSortOption) *NullableUserSortOption {
	return &NullableUserSortOption{value: val, isSet: true}
}

func (v NullableUserSortOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserSortOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

