/*
Digiseg API

### Digiseg API documentation  # Introduction  This API let you harness the power of Digisegs powerful and tracking-free segmentation engine.  Audiences by Digiseg are available in 50+ countries, probablistically mapping neighborhood characteristics to the IP addresses observed on the internet - Household targeting & measurement for the post-cookie world.  ## Developer SDKs  In addition to using these APIs directly through any HTTP client, we provide a set of API client SDKs for popular programming languages:  <div class=\"api-clients\">   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-python\">     <i class=\"api-client-sdk-logo devicon-python-plain\"></i>     <p>API client for Python</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-go\">     <i class=\"api-client-sdk-logo devicon-go-original-wordmark\"></i>     <p>API client for Go</p>   </a> </div> <div class=\"api-clients-breaker\" />  ## Audience taxonomy  For a catalog of Digisegs audiences, refer to the [Audience list](https://digiseg.io/audiences-list).  There is also an interactive [Audience builder](https://digiseg.io/cookieless-audience-builder/) which lets you discover the targeting reach and power of combining various household characteristics into composite audiences. 

API version: 1.0.0
Contact: support@digiseg.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListPaginationMetaPage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListPaginationMetaPage{}

// ListPaginationMetaPage struct for ListPaginationMetaPage
type ListPaginationMetaPage struct {
	// The total amount of elements in the list (the returned `data` may be paginated)
	Total *int32 `json:"total,omitempty"`
	FirstCursor *string `json:"first_cursor,omitempty"`
	// Indicates the cursor value to use in `page[after]`, when paginating to the next page
	LastCursor *string `json:"last_cursor,omitempty"`
	// Indicates whether the list has been truncated (ie. more items can be queried using pagination)
	RangeTruncated bool `json:"rangeTruncated"`
}

type _ListPaginationMetaPage ListPaginationMetaPage

// NewListPaginationMetaPage instantiates a new ListPaginationMetaPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListPaginationMetaPage(rangeTruncated bool) *ListPaginationMetaPage {
	this := ListPaginationMetaPage{}
	this.RangeTruncated = rangeTruncated
	return &this
}

// NewListPaginationMetaPageWithDefaults instantiates a new ListPaginationMetaPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListPaginationMetaPageWithDefaults() *ListPaginationMetaPage {
	this := ListPaginationMetaPage{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ListPaginationMetaPage) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPaginationMetaPage) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ListPaginationMetaPage) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *ListPaginationMetaPage) SetTotal(v int32) {
	o.Total = &v
}

// GetFirstCursor returns the FirstCursor field value if set, zero value otherwise.
func (o *ListPaginationMetaPage) GetFirstCursor() string {
	if o == nil || IsNil(o.FirstCursor) {
		var ret string
		return ret
	}
	return *o.FirstCursor
}

// GetFirstCursorOk returns a tuple with the FirstCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPaginationMetaPage) GetFirstCursorOk() (*string, bool) {
	if o == nil || IsNil(o.FirstCursor) {
		return nil, false
	}
	return o.FirstCursor, true
}

// HasFirstCursor returns a boolean if a field has been set.
func (o *ListPaginationMetaPage) HasFirstCursor() bool {
	if o != nil && !IsNil(o.FirstCursor) {
		return true
	}

	return false
}

// SetFirstCursor gets a reference to the given string and assigns it to the FirstCursor field.
func (o *ListPaginationMetaPage) SetFirstCursor(v string) {
	o.FirstCursor = &v
}

// GetLastCursor returns the LastCursor field value if set, zero value otherwise.
func (o *ListPaginationMetaPage) GetLastCursor() string {
	if o == nil || IsNil(o.LastCursor) {
		var ret string
		return ret
	}
	return *o.LastCursor
}

// GetLastCursorOk returns a tuple with the LastCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPaginationMetaPage) GetLastCursorOk() (*string, bool) {
	if o == nil || IsNil(o.LastCursor) {
		return nil, false
	}
	return o.LastCursor, true
}

// HasLastCursor returns a boolean if a field has been set.
func (o *ListPaginationMetaPage) HasLastCursor() bool {
	if o != nil && !IsNil(o.LastCursor) {
		return true
	}

	return false
}

// SetLastCursor gets a reference to the given string and assigns it to the LastCursor field.
func (o *ListPaginationMetaPage) SetLastCursor(v string) {
	o.LastCursor = &v
}

// GetRangeTruncated returns the RangeTruncated field value
func (o *ListPaginationMetaPage) GetRangeTruncated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RangeTruncated
}

// GetRangeTruncatedOk returns a tuple with the RangeTruncated field value
// and a boolean to check if the value has been set.
func (o *ListPaginationMetaPage) GetRangeTruncatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RangeTruncated, true
}

// SetRangeTruncated sets field value
func (o *ListPaginationMetaPage) SetRangeTruncated(v bool) {
	o.RangeTruncated = v
}

func (o ListPaginationMetaPage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListPaginationMetaPage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.FirstCursor) {
		toSerialize["first_cursor"] = o.FirstCursor
	}
	if !IsNil(o.LastCursor) {
		toSerialize["last_cursor"] = o.LastCursor
	}
	toSerialize["rangeTruncated"] = o.RangeTruncated
	return toSerialize, nil
}

func (o *ListPaginationMetaPage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rangeTruncated",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListPaginationMetaPage := _ListPaginationMetaPage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListPaginationMetaPage)

	if err != nil {
		return err
	}

	*o = ListPaginationMetaPage(varListPaginationMetaPage)

	return err
}

type NullableListPaginationMetaPage struct {
	value *ListPaginationMetaPage
	isSet bool
}

func (v NullableListPaginationMetaPage) Get() *ListPaginationMetaPage {
	return v.value
}

func (v *NullableListPaginationMetaPage) Set(val *ListPaginationMetaPage) {
	v.value = val
	v.isSet = true
}

func (v NullableListPaginationMetaPage) IsSet() bool {
	return v.isSet
}

func (v *NullableListPaginationMetaPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPaginationMetaPage(val *ListPaginationMetaPage) *NullableListPaginationMetaPage {
	return &NullableListPaginationMetaPage{value: val, isSet: true}
}

func (v NullableListPaginationMetaPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListPaginationMetaPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


