/*
Digiseg API

### Digiseg API documentation  # Introduction  This API let you harness the power of Digisegs powerful and tracking-free segmentation engine.  Audiences by Digiseg are available in 50+ countries, probablistically mapping neighborhood characteristics to the IP addresses observed on the internet - Household targeting & measurement for the post-cookie world.  ## Developer SDKs  In addition to using these APIs directly through any HTTP client, we provide a set of API client SDKs for popular programming languages:  <div class=\"api-clients\">   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-python\">     <i class=\"api-client-sdk-logo devicon-python-plain\"></i>     <p>API client for Python</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-go\">     <i class=\"api-client-sdk-logo devicon-go-original-wordmark\"></i>     <p>API client for Go</p>   </a> </div> <div class=\"api-clients-breaker\" />  ## Audience taxonomy  For a catalog of Digisegs audiences, refer to the [Audience list](https://digiseg.io/audiences-list).  There is also an interactive [Audience builder](https://digiseg.io/cookieless-audience-builder/) which lets you discover the targeting reach and power of combining various household characteristics into composite audiences. 

API version: 1.0.0
Contact: support@digiseg.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CampaignFrequencyStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CampaignFrequencyStats{}

// CampaignFrequencyStats struct for CampaignFrequencyStats
type CampaignFrequencyStats struct {
	// The average frequency of impressions per user 
	AverageFrequency *float32 `json:"average_frequency,omitempty"`
	// A listing of each frequency observed and the relevant measurements for each 
	Frequencies []FrequencyStats `json:"frequencies,omitempty"`
	// The number of users that have generated impressions at a frequency value greater than those represented in `frequencies`. 
	CountAboveCap *int32 `json:"count_above_cap,omitempty"`
}

// NewCampaignFrequencyStats instantiates a new CampaignFrequencyStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignFrequencyStats() *CampaignFrequencyStats {
	this := CampaignFrequencyStats{}
	return &this
}

// NewCampaignFrequencyStatsWithDefaults instantiates a new CampaignFrequencyStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignFrequencyStatsWithDefaults() *CampaignFrequencyStats {
	this := CampaignFrequencyStats{}
	return &this
}

// GetAverageFrequency returns the AverageFrequency field value if set, zero value otherwise.
func (o *CampaignFrequencyStats) GetAverageFrequency() float32 {
	if o == nil || IsNil(o.AverageFrequency) {
		var ret float32
		return ret
	}
	return *o.AverageFrequency
}

// GetAverageFrequencyOk returns a tuple with the AverageFrequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignFrequencyStats) GetAverageFrequencyOk() (*float32, bool) {
	if o == nil || IsNil(o.AverageFrequency) {
		return nil, false
	}
	return o.AverageFrequency, true
}

// HasAverageFrequency returns a boolean if a field has been set.
func (o *CampaignFrequencyStats) HasAverageFrequency() bool {
	if o != nil && !IsNil(o.AverageFrequency) {
		return true
	}

	return false
}

// SetAverageFrequency gets a reference to the given float32 and assigns it to the AverageFrequency field.
func (o *CampaignFrequencyStats) SetAverageFrequency(v float32) {
	o.AverageFrequency = &v
}

// GetFrequencies returns the Frequencies field value if set, zero value otherwise.
func (o *CampaignFrequencyStats) GetFrequencies() []FrequencyStats {
	if o == nil || IsNil(o.Frequencies) {
		var ret []FrequencyStats
		return ret
	}
	return o.Frequencies
}

// GetFrequenciesOk returns a tuple with the Frequencies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignFrequencyStats) GetFrequenciesOk() ([]FrequencyStats, bool) {
	if o == nil || IsNil(o.Frequencies) {
		return nil, false
	}
	return o.Frequencies, true
}

// HasFrequencies returns a boolean if a field has been set.
func (o *CampaignFrequencyStats) HasFrequencies() bool {
	if o != nil && !IsNil(o.Frequencies) {
		return true
	}

	return false
}

// SetFrequencies gets a reference to the given []FrequencyStats and assigns it to the Frequencies field.
func (o *CampaignFrequencyStats) SetFrequencies(v []FrequencyStats) {
	o.Frequencies = v
}

// GetCountAboveCap returns the CountAboveCap field value if set, zero value otherwise.
func (o *CampaignFrequencyStats) GetCountAboveCap() int32 {
	if o == nil || IsNil(o.CountAboveCap) {
		var ret int32
		return ret
	}
	return *o.CountAboveCap
}

// GetCountAboveCapOk returns a tuple with the CountAboveCap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignFrequencyStats) GetCountAboveCapOk() (*int32, bool) {
	if o == nil || IsNil(o.CountAboveCap) {
		return nil, false
	}
	return o.CountAboveCap, true
}

// HasCountAboveCap returns a boolean if a field has been set.
func (o *CampaignFrequencyStats) HasCountAboveCap() bool {
	if o != nil && !IsNil(o.CountAboveCap) {
		return true
	}

	return false
}

// SetCountAboveCap gets a reference to the given int32 and assigns it to the CountAboveCap field.
func (o *CampaignFrequencyStats) SetCountAboveCap(v int32) {
	o.CountAboveCap = &v
}

func (o CampaignFrequencyStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CampaignFrequencyStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AverageFrequency) {
		toSerialize["average_frequency"] = o.AverageFrequency
	}
	if !IsNil(o.Frequencies) {
		toSerialize["frequencies"] = o.Frequencies
	}
	if !IsNil(o.CountAboveCap) {
		toSerialize["count_above_cap"] = o.CountAboveCap
	}
	return toSerialize, nil
}

type NullableCampaignFrequencyStats struct {
	value *CampaignFrequencyStats
	isSet bool
}

func (v NullableCampaignFrequencyStats) Get() *CampaignFrequencyStats {
	return v.value
}

func (v *NullableCampaignFrequencyStats) Set(val *CampaignFrequencyStats) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignFrequencyStats) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignFrequencyStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignFrequencyStats(val *CampaignFrequencyStats) *NullableCampaignFrequencyStats {
	return &NullableCampaignFrequencyStats{value: val, isSet: true}
}

func (v NullableCampaignFrequencyStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignFrequencyStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


