/*
Digiseg API

### Digiseg API documentation  # Introduction  This API let you harness the power of Digisegs powerful and tracking-free segmentation engine.  Audiences by Digiseg are available in 50+ countries, probablistically mapping neighborhood characteristics to the IP addresses observed on the internet - Household targeting & measurement for the post-cookie world.  ## Developer SDKs  In addition to using these APIs directly through any HTTP client, we provide a set of API client SDKs for popular programming languages:  <div class=\"api-clients\">   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-python\">     <i class=\"api-client-sdk-logo devicon-python-plain\"></i>     <p>API client for Python</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-ts\">     <i class=\"api-client-sdk-logo devicon-typescript-plain\"></i>     <p>API client for TypeScript</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-go\">     <i class=\"api-client-sdk-logo devicon-go-original-wordmark\"></i>     <p>API client for Go</p>   </a> </div> <div class=\"api-clients-breaker\" /> 

API version: 1.0.0
Contact: support@digiseg.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// StudyLifecycleStage The life cycle stage of the study. 
type StudyLifecycleStage string

// List of StudyLifecycleStage
const (
	STUDYLIFECYCLESTAGE_PENDING StudyLifecycleStage = "pending"
	STUDYLIFECYCLESTAGE_ACTIVE StudyLifecycleStage = "active"
	STUDYLIFECYCLESTAGE_PAUSED StudyLifecycleStage = "paused"
	STUDYLIFECYCLESTAGE_FINISHED StudyLifecycleStage = "finished"
)

// All allowed values of StudyLifecycleStage enum
var AllowedStudyLifecycleStageEnumValues = []StudyLifecycleStage{
	"pending",
	"active",
	"paused",
	"finished",
}

func (v *StudyLifecycleStage) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := StudyLifecycleStage(value)
	for _, existing := range AllowedStudyLifecycleStageEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid StudyLifecycleStage", value)
}

// NewStudyLifecycleStageFromValue returns a pointer to a valid StudyLifecycleStage
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewStudyLifecycleStageFromValue(v string) (*StudyLifecycleStage, error) {
	ev := StudyLifecycleStage(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for StudyLifecycleStage: valid values are %v", v, AllowedStudyLifecycleStageEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v StudyLifecycleStage) IsValid() bool {
	for _, existing := range AllowedStudyLifecycleStageEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to StudyLifecycleStage value
func (v StudyLifecycleStage) Ptr() *StudyLifecycleStage {
	return &v
}

type NullableStudyLifecycleStage struct {
	value *StudyLifecycleStage
	isSet bool
}

func (v NullableStudyLifecycleStage) Get() *StudyLifecycleStage {
	return v.value
}

func (v *NullableStudyLifecycleStage) Set(val *StudyLifecycleStage) {
	v.value = val
	v.isSet = true
}

func (v NullableStudyLifecycleStage) IsSet() bool {
	return v.isSet
}

func (v *NullableStudyLifecycleStage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStudyLifecycleStage(val *StudyLifecycleStage) *NullableStudyLifecycleStage {
	return &NullableStudyLifecycleStage{value: val, isSet: true}
}

func (v NullableStudyLifecycleStage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStudyLifecycleStage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

