/*
Digiseg API

### Digiseg API documentation  # Introduction  This API let you harness the power of Digisegs powerful and tracking-free segmentation engine.  Audiences by Digiseg are available in 50+ countries, probablistically mapping neighborhood characteristics to the IP addresses observed on the internet - Household targeting & measurement for the post-cookie world.  ## Developer SDKs  In addition to using these APIs directly through any HTTP client, we provide a set of API client SDKs for popular programming languages:  <div class=\"api-clients\">   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-python\">     <i class=\"api-client-sdk-logo devicon-python-plain\"></i>     <p>API client for Python</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-ts\">     <i class=\"api-client-sdk-logo devicon-typescript-plain\"></i>     <p>API client for TypeScript</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-go\">     <i class=\"api-client-sdk-logo devicon-go-original-wordmark\"></i>     <p>API client for Go</p>   </a> </div> <div class=\"api-clients-breaker\" /> 

API version: 1.0.0
Contact: support@digiseg.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the PopulationSourceBusinessCategorySet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PopulationSourceBusinessCategorySet{}

// PopulationSourceBusinessCategorySet struct for PopulationSourceBusinessCategorySet
type PopulationSourceBusinessCategorySet struct {
	Size PopulationSourceBusinessCategorySetSize `json:"size"`
	AdditionalProperties map[string]interface{}
}

type _PopulationSourceBusinessCategorySet PopulationSourceBusinessCategorySet

// NewPopulationSourceBusinessCategorySet instantiates a new PopulationSourceBusinessCategorySet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPopulationSourceBusinessCategorySet(size PopulationSourceBusinessCategorySetSize) *PopulationSourceBusinessCategorySet {
	this := PopulationSourceBusinessCategorySet{}
	this.Size = size
	return &this
}

// NewPopulationSourceBusinessCategorySetWithDefaults instantiates a new PopulationSourceBusinessCategorySet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPopulationSourceBusinessCategorySetWithDefaults() *PopulationSourceBusinessCategorySet {
	this := PopulationSourceBusinessCategorySet{}
	return &this
}

// GetSize returns the Size field value
func (o *PopulationSourceBusinessCategorySet) GetSize() PopulationSourceBusinessCategorySetSize {
	if o == nil {
		var ret PopulationSourceBusinessCategorySetSize
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *PopulationSourceBusinessCategorySet) GetSizeOk() (*PopulationSourceBusinessCategorySetSize, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *PopulationSourceBusinessCategorySet) SetSize(v PopulationSourceBusinessCategorySetSize) {
	o.Size = v
}

func (o PopulationSourceBusinessCategorySet) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PopulationSourceBusinessCategorySet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["size"] = o.Size

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PopulationSourceBusinessCategorySet) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"size",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPopulationSourceBusinessCategorySet := _PopulationSourceBusinessCategorySet{}

	err = json.Unmarshal(data, &varPopulationSourceBusinessCategorySet)

	if err != nil {
		return err
	}

	*o = PopulationSourceBusinessCategorySet(varPopulationSourceBusinessCategorySet)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "size")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePopulationSourceBusinessCategorySet struct {
	value *PopulationSourceBusinessCategorySet
	isSet bool
}

func (v NullablePopulationSourceBusinessCategorySet) Get() *PopulationSourceBusinessCategorySet {
	return v.value
}

func (v *NullablePopulationSourceBusinessCategorySet) Set(val *PopulationSourceBusinessCategorySet) {
	v.value = val
	v.isSet = true
}

func (v NullablePopulationSourceBusinessCategorySet) IsSet() bool {
	return v.isSet
}

func (v *NullablePopulationSourceBusinessCategorySet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePopulationSourceBusinessCategorySet(val *PopulationSourceBusinessCategorySet) *NullablePopulationSourceBusinessCategorySet {
	return &NullablePopulationSourceBusinessCategorySet{value: val, isSet: true}
}

func (v NullablePopulationSourceBusinessCategorySet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePopulationSourceBusinessCategorySet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


