/*
Digiseg API

### Digiseg API documentation  # Introduction  This API let you harness the power of Digisegs powerful and tracking-free segmentation engine.  Audiences by Digiseg are available in 50+ countries, probablistically mapping neighborhood characteristics to the IP addresses observed on the internet - Household targeting & measurement for the post-cookie world.  ## Developer SDKs  In addition to using these APIs directly through any HTTP client, we provide a set of API client SDKs for popular programming languages:  <div class=\"api-clients\">   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-python\">     <i class=\"api-client-sdk-logo devicon-python-plain\"></i>     <p>API client for<br/>Python</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-ts\">     <i class=\"api-client-sdk-logo devicon-typescript-plain\"></i>     <p>API client for<br/>TypeScript</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-go\">     <i class=\"api-client-sdk-logo devicon-go-original-wordmark\"></i>     <p>API client for<br/>Go</p>   </a>   <a class=\"api-client-box\" href=\"https://github.com/digiseg-labs/api-client-dotnet\">     <i class=\"api-client-sdk-logo devicon-dot-net-plain\"></i>     <p>API client for<br/>.NET</p>   </a> </div> <div class=\"api-clients-breaker\" /> 

API version: 1.0.0
Contact: support@digiseg.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the StudyAIImportantNumber type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StudyAIImportantNumber{}

// StudyAIImportantNumber struct for StudyAIImportantNumber
type StudyAIImportantNumber struct {
	Label string `json:"label"`
	Value string `json:"value"`
	Unit string `json:"unit"`
	Context string `json:"context"`
	AdditionalProperties map[string]interface{}
}

type _StudyAIImportantNumber StudyAIImportantNumber

// NewStudyAIImportantNumber instantiates a new StudyAIImportantNumber object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStudyAIImportantNumber(label string, value string, unit string, context string) *StudyAIImportantNumber {
	this := StudyAIImportantNumber{}
	this.Label = label
	this.Value = value
	this.Unit = unit
	this.Context = context
	return &this
}

// NewStudyAIImportantNumberWithDefaults instantiates a new StudyAIImportantNumber object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStudyAIImportantNumberWithDefaults() *StudyAIImportantNumber {
	this := StudyAIImportantNumber{}
	return &this
}

// GetLabel returns the Label field value
func (o *StudyAIImportantNumber) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *StudyAIImportantNumber) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *StudyAIImportantNumber) SetLabel(v string) {
	o.Label = v
}

// GetValue returns the Value field value
func (o *StudyAIImportantNumber) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *StudyAIImportantNumber) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *StudyAIImportantNumber) SetValue(v string) {
	o.Value = v
}

// GetUnit returns the Unit field value
func (o *StudyAIImportantNumber) GetUnit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Unit
}

// GetUnitOk returns a tuple with the Unit field value
// and a boolean to check if the value has been set.
func (o *StudyAIImportantNumber) GetUnitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Unit, true
}

// SetUnit sets field value
func (o *StudyAIImportantNumber) SetUnit(v string) {
	o.Unit = v
}

// GetContext returns the Context field value
func (o *StudyAIImportantNumber) GetContext() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Context
}

// GetContextOk returns a tuple with the Context field value
// and a boolean to check if the value has been set.
func (o *StudyAIImportantNumber) GetContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Context, true
}

// SetContext sets field value
func (o *StudyAIImportantNumber) SetContext(v string) {
	o.Context = v
}

func (o StudyAIImportantNumber) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StudyAIImportantNumber) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["label"] = o.Label
	toSerialize["value"] = o.Value
	toSerialize["unit"] = o.Unit
	toSerialize["context"] = o.Context

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StudyAIImportantNumber) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"label",
		"value",
		"unit",
		"context",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStudyAIImportantNumber := _StudyAIImportantNumber{}

	err = json.Unmarshal(data, &varStudyAIImportantNumber)

	if err != nil {
		return err
	}

	*o = StudyAIImportantNumber(varStudyAIImportantNumber)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "label")
		delete(additionalProperties, "value")
		delete(additionalProperties, "unit")
		delete(additionalProperties, "context")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStudyAIImportantNumber struct {
	value *StudyAIImportantNumber
	isSet bool
}

func (v NullableStudyAIImportantNumber) Get() *StudyAIImportantNumber {
	return v.value
}

func (v *NullableStudyAIImportantNumber) Set(val *StudyAIImportantNumber) {
	v.value = val
	v.isSet = true
}

func (v NullableStudyAIImportantNumber) IsSet() bool {
	return v.isSet
}

func (v *NullableStudyAIImportantNumber) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStudyAIImportantNumber(val *StudyAIImportantNumber) *NullableStudyAIImportantNumber {
	return &NullableStudyAIImportantNumber{value: val, isSet: true}
}

func (v NullableStudyAIImportantNumber) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStudyAIImportantNumber) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


